authors:
  elias:
    name: Elias Gino Cripotos
    description: Community Manager @ MobilityData
    avatar: https://avatars.githubusercontent.com/u/130911698?v=4
  mobilitydata:
    name: MobilityData
    description: Steward of GTFS
    avatar: https://avatars.githubusercontent.com/u/41021710?s=200&v=4