name: 'Close outdated PRs'
description: 'Closes pull requests with the specified label that are older than 23 hours.'
inputs:
  github-token: # id of output
    description: 'GitHub Token with repo scope.'
    required: true
  label-name: # id of output
    description: 'The label of PRs to evaluate for closing.'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
