site_name: General Transit Feed Specification
site_url: https://gtfs.org
repo_url: https://github.com/google/transit
repo_name: GTFS Repository
docs_dir: ../../docs/en       # Where to find the markdown files
site_dir: ../../generated/    # Where to put the HTML files

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

theme:
  language: en
  custom_dir: ../../overrides/
  logo: assets/images/logo.png
  logo_light_mode: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: gtfs
      primary: custom
      accent: custom
  name: material
  font:
    text: Mulish
    code: SF Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/footer.css
extra_javascript:
  - assets/javascript/anchor-redirects.js
  - assets/javascript/hide-announcement.js
  - assets/javascript/fix-search-path.js
extra:
  analytics:
    provider: google
    property: G-DRBTC7SSDT
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to track visits, stored anonymously. With your consent, you're helping us to make our documentation better. See our <a href="https://mobilitydata.org/privacy-policy/">Privacy Policy</a>.
    actions:
        - accept
        - reject
        - manage
  social:
    - icon: fontawesome/solid/square-rss
      name: GTFS Digest RSS feed
      link: https://gtfs.org/blog/feed_rss_created.xml
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://share.mobilitydata.org/slack
  alternate:
      - name: English
        link: /
        lang: en
      - name: Français
        link: /fr/
        lang: fr
      - name: Español
        link: /es/
        lang: es
      - name: 日本語
        link: /ja/
        lang: ja
      - name: Deutsch (wird bald verfügbar sein)
        link: /de/
        lang: de
      - name: Português (em breve)
        link: /pt/
        lang: pt
      - name: Русский (будет добавлен позже)
        link: /ru/
        lang: ru
      - name: Bahasa Indonesia (akan segera hadir)
        link: /id/
        lang: id
      - name: 한국어 (곧 제공 예정)
        link: /ko/
        lang: ko
      - name: 中文 - 简体（即将推出）
        link: /zh/
        lang: zh
      - name: 中文 - 繁體（即將推出）
        link: /zh-TW/
        lang: zh-TW

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - external-markdown
  - privacy:
      assets: false
      links_attr_map:
        target: _blank
  - search:
      lang: 
        - en
  - blog:
      enabled: true
      archive: false
      blog_dir: blog
      post_dir: "{blog}/posts"
      authors_file: "blog/.authors.yml"
      authors_profiles: true
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      categories_allowed:
        - Announcements
        - GTFS
        - GTFS Digest
        - GTFS Realtime
        - GTFS Schedule
  - rss:
        match_path: "blog/posts/*"
        date_from_meta:
          as_creation: date.created
          as_update: date.updated

nav:
  - Home: index.md
  - Getting started:
    - What is GTFS?: getting-started/what-is-GTFS.md
    - Why use GTFS?: getting-started/why-use-GTFS.md
    - How to produce GTFS?: 
      - Create: getting-started/create.md
      - Validate: getting-started/validate.md
      - Publish: getting-started/publish.md
    - What can GTFS do?:
      - Overview: getting-started/features/overview.md
      - Base: getting-started/features/base.md
      - Base add-ons: getting-started/features/base-add-ons.md
      - Accessibility: getting-started/features/accessibility.md
      - Fares: getting-started/features/fares.md
      - Pathways: getting-started/features/pathways.md
      - Flexible services: getting-started/features/flexible-services.md
    - Example GTFS feed: getting-started/example-feed.md
  - Technical Documentation:
    - Overview: documentation/overview.md
    - Schedule:
      - Reference: documentation/schedule/reference.md
      - Best Practices: documentation/schedule/schedule-best-practices.md
      - Data examples:
        - Attributions: documentation/schedule/examples/attributions.md
        - Continuous stops: documentation/schedule/examples/continuous-stops.md
        - Demand responsive services: documentation/schedule/examples/flex.md
        - Fares (v2):
          - Introduction: documentation/schedule/examples/fares/intro.md
          - Fare Media: documentation/schedule/examples/fares/fare-media.md
          - Fare Products: documentation/schedule/examples/fares/fare-products.md
          - Rider Categories: documentation/schedule/examples/fares/rider-categories.md
          - Route-Based Fares: documentation/schedule/examples/fares/route-based-fares.md
          - Zone-Based Fares: documentation/schedule/examples/fares/zone-based-fares.md
          - Time-Based Fares: documentation/schedule/examples/fares/time-based-fares.md
          - Fare Transfers: documentation/schedule/examples/fares/fare-transfers.md
          - Archived examples: documentation/schedule/examples/fares/archived-fares-examples.md
        - Legacy Fares (v1): documentation/schedule/examples/fares-v1.md
        - Feed information: documentation/schedule/examples/feed-info.md
        - Frequencies: documentation/schedule/examples/frequencies.md
        - Pathways: documentation/schedule/examples/pathways.md
        - Routes, Stops & Trips: documentation/schedule/examples/routes-stops-trips.md
        - Shapes: documentation/schedule/examples/shapes.md
        - Text-to-speech: documentation/schedule/examples/text-to-speech.md
        - Transfers: documentation/schedule/examples/transfers.md
        - Translations: documentation/schedule/examples/translations.md
      - Change history:
        - Recent additions: documentation/schedule/change-history/recent-additions.md
        - Full revision history: documentation/schedule/change-history/revision-history.md
    - Realtime:
      - Reference: documentation/realtime/reference.md
      - Best Practices: documentation/realtime/realtime-best-practices.md
      - Feed Entities: 
          - Overview: documentation/realtime/feed-entities/overview.md
          - Trip Updates: documentation/realtime/feed-entities/trip-updates.md
          - Service Alerts: documentation/realtime/feed-entities/service-alerts.md
          - Vehicle Positions: documentation/realtime/feed-entities/vehicle-positions.md
          - Trip Modifications: documentation/realtime/feed-entities/trip-modifications.md
      - Protobuf: documentation/realtime/proto.md
      - Language Bindings:
        - Overview: documentation/realtime/language-bindings/overview.md
        - .NET: documentation/realtime/language-bindings/dotnet.md
        - Java: documentation/realtime/language-bindings/java.md
        - JavaScript/Node.js: documentation/realtime/language-bindings/nodejs.md
        - Python: documentation/realtime/language-bindings/python.md
        - Golang: documentation/realtime/language-bindings/golang.md
        - Ruby: documentation/realtime/language-bindings/ruby.md
        - PHP: documentation/realtime/language-bindings/php.md
      - Data examples:
        - Service alerts: documentation/realtime/examples/service-alerts.md
        - Trip updates: documentation/realtime/examples/trip-updates.md
        - Migration duplicated: documentation/realtime/examples/migration-duplicated.md
      - Change history:
        - Recent Additions: documentation/realtime/change-history/recent-additions.md
        - Full revision history: documentation/realtime/change-history/revision-history.md
  - Community:
    - Get involved: community/get-involved.md
    - Governance:
      - GTFS Schedule Amendment Process: community/governance/gtfs-schedule-amendment-process.md
      - GTFS Realtime Amendment Process: community/governance/gtfs-realtime-amendment-process.md
    - Extensions:
      - Overview: community/extensions/overview.md
      - Fares v2: community/extensions/fares-v2.md
      - Flex: community/extensions/flex.md
  - Resources:
    - Overview: resources/overview.md
    - Getting Started: resources/getting-started.md
    - Community: resources/community.md
    - Data: resources/data.md
    - Software for Creating APIs: resources/software-for-creating-apis.md
    - Agency Tools: resources/agency-tools.md
    - Hardware: resources/hardware.md
    - Apps: resources/apps.md
    - SDKs: resources/sdk.md
    - Visualizations: resources/visualizations.md
    - GTFS: resources/gtfs.md
    - GTFS Realtime: resources/gtfs-realtime.md
    - SIRI: resources/siri.md
    - Multimodal: resources/multimodal.md
    - Other: resources/other.md
  - About:
      - about/index.md
  - Blog:
      - blog/index.md
not_in_nav: |
  /blog/registration-complete.md