site_name: General Transit Feed Specification
site_url: https://gtfs.org
repo_url: https://github.com/google/transit
repo_name: Répertoire GitHub GTFS
docs_dir: ../../docs/fr       # Where to find the markdown files
site_dir: ../../generated/fr  # Where to put the HTML files

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

theme:
  language: fr
  custom_dir: ../../overrides/
  logo: assets/images/logo.png
  logo_light_mode: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: gtfs
      primary: custom
      accent: custom
  name: material
  font:
    text: Mulish
    code: SF Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/footer.css
extra_javascript:
  - assets/javascript/anchor-redirects.js
extra:
  analytics:
    provider: google
    property: G-DRBTC7SSDT
  consent:
    title: Consentement aux cookies
    description: >-
      Nous utilisons des cookies pour suivre les visites, stockés de manière anonyme. Avec votre consentement, vous nous aidez à améliorer notre documentation. Voir notre <a href="https://mobilitydata.org/privacy-policy/">Politique sur la vie privée</a>.
    actions:
        - accept
        - reject
        - manage
  social:
    - icon: fontawesome/solid/square-rss
      name: GTFS Digest RSS feed
      link: https://gtfs.org/blog/feed_rss_created.xml
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://share.mobilitydata.org/slack
  alternate:
      - name: English
        link: /
        lang: en
      - name: Français
        link: /fr/
        lang: fr
      - name: Español
        link: /es/
        lang: es
      - name: 日本語
        link: /ja/
        lang: ja
      - name: Deutsch (wird bald verfügbar sein)
        link: /de/
        lang: de
      - name: Português (em breve)
        link: /pt/
        lang: pt
      - name: Русский (будет добавлен позже)
        link: /ru/
        lang: ru
      - name: Bahasa Indonesia (akan segera hadir)
        link: /id/
        lang: id
      - name: 한국어 (곧 제공 예정)
        link: /ko/
        lang: ko
      - name: 中文 - 简体（即将推出）
        link: /zh/
        lang: zh
      - name: 中文 - 繁體（即將推出）
        link: /zh-TW/
        lang: zh-TW

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - external-markdown
  - privacy:
      assets: false
      links_attr_map:
        target: _blank
  - search:
      lang:
        - fr

nav:
  - Accueil: index.md
  - Premiers pas:
    - Qu'est-ce que GTFS ?: getting-started/what-is-GTFS.md
    - Pourquoi utiliser GTFS ?: getting-started/why-use-GTFS.md
    - Comment produire du GTFS ?:
      - Créer: getting-started/create.md
      - Valider: getting-started/validate.md
      - Publier: getting-started/publish.md
    - Que peut faire GTFS ?:
      - Aperçu: getting-started/features/overview.md
      - Base: getting-started/features/base.md
      - Modules Complémentaires à Base: getting-started/features/base-add-ons.md
      - Accessibilité: getting-started/features/accessibility.md
      - Tarifs: getting-started/features/fares.md
      - Pathways: getting-started/features/pathways.md
      - Services flexibles: getting-started/features/flexible-services.md
    - Exemple de flux GTFS: getting-started/example-feed.md
  - Documentation technique:
    - Aperçu: documentation/overview.md
    - Schedule:
      - Référence: documentation/schedule/reference.md
      - Bonnes pratiques: documentation/schedule/schedule-best-practices.md
      - Exemples de données:
        - Attributions: documentation/schedule/examples/attributions.md
        - Arrêts continus: documentation/schedule/examples/continuous-stops.md
        - Transport à la demande: documentation/schedule/examples/flex.md
        - Tarifs (v2):
          - Introduction: documentation/schedule/examples/fares/intro.md
          - Tarif Média: documentation/schedule/examples/fares/fare-media.md
          - Produits tarifaires: documentation/schedule/examples/fares/fare-products.md
          - Catégories d'usagers: documentation/schedule/examples/fares/rider-categories.md
          - Tarifs Basés sur l'Itinéraire: documentation/schedule/examples/fares/route-based-fares.md
          - Tarifs Basés a Zones: documentation/schedule/examples/fares/zone-based-fares.md
          - Tarifs Basés sur le Temps: documentation/schedule/examples/fares/time-based-fares.md
          - Transferts Tarifaires: documentation/schedule/examples/fares/fare-transfers.md
          - Exemples archivés: documentation/schedule/examples/fares/archived-fares-examples.md
        - Tarifs - ancienne version (v1): documentation/schedule/examples/fares-v1.md
        - Informations sur le flux: documentation/schedule/examples/feed-info.md
        - Fréquences: documentation/schedule/examples/frequencies.md
        - Pathways: documentation/schedule/examples/pathways.md
        - Lignes, arrêts et trajets: documentation/schedule/examples/routes-stops-trips.md
        - Tracé des lignes (Shapes): documentation/schedule/examples/shapes.md
        - Synthèse vocale: documentation/schedule/examples/text-to-speech.md
        - Transferts: documentation/schedule/examples/transfers.md
        - Traductions: documentation/schedule/examples/translations.md
      - Historique des changements:
        - Ajouts récents: documentation/schedule/change-history/recent-additions.md
        - Historique complet des révisions: documentation/schedule/change-history/revision-history.md
    - Realtime:
      - Référence: documentation/realtime/reference.md
      - Bonnes pratiques: documentation/realtime/realtime-best-practices.md
      - Entités de flux:
          - Aperçu: documentation/realtime/feed-entities/overview.md
          - Mises à jour du voyage: documentation/realtime/feed-entities/trip-updates.md
          - Alertes de service: documentation/realtime/feed-entities/service-alerts.md
          - Positions des véhicules: documentation/realtime/feed-entities/vehicle-positions.md
          - Trip Modifications: documentation/realtime/feed-entities/trip-modifications.md
      - Protobuf: documentation/realtime/proto.md
      - Binding de langage:
        - Aperçu: documentation/realtime/language-bindings/overview.md
        - .NET: documentation/realtime/language-bindings/dotnet.md
        - Java: documentation/realtime/language-bindings/java.md
        - JavaScript/Node.js: documentation/realtime/language-bindings/nodejs.md
        - Python: documentation/realtime/language-bindings/python.md
        - Golang: documentation/realtime/language-bindings/golang.md
        - Ruby: documentation/realtime/language-bindings/ruby.md
        - PHP: documentation/realtime/language-bindings/php.md
      - Exemples de données:
        - Alertes de service: documentation/realtime/examples/service-alerts.md
        - Mises à jour du voyage: documentation/realtime/examples/trip-updates.md
        - Migration dupliquée: documentation/realtime/examples/migration-duplicated.md
      - Historique des changements:
        - Ajouts récents: documentation/realtime/change-history/recent-additions.md
        - Historique complet des révisions: documentation/realtime/change-history/revision-history.md
  - Communauté:
    - S'impliquer: community/get-involved.md
    - Gouvernance:
      - Processus de modification GTFS Schedule: community/governance/gtfs-schedule-amendment-process.md
      - Processus de modification GTFS Realtime: community/governance/gtfs-realtime-amendment-process.md
    - Extensions:
      - Aperçu: community/extensions/overview.md
      - Fares v2: community/extensions/fares-v2.md
      - Flex: community/extensions/flex.md
  - Ressources:
    - Aperçu: resources/overview.md
    - Premiers pas: resources/getting-started.md
    - Communauté: resources/community.md
    - Données: resources/data.md
    - Logiciel de création d'API: resources/software-for-creating-apis.md
    - Outils pour les agences: resources/agency-tools.md
    - Matériel: resources/hardware.md
    - Apps: resources/apps.md
    - SDKs: resources/sdk.md
    - Visualisations: resources/visualizations.md
    - GTFS: resources/gtfs.md
    - GTFS Realtime: resources/gtfs-realtime.md
    - SIRI: resources/siri.md
    - Multimodal: resources/multimodal.md
    - Autre: resources/other.md
  - À propos:
      - about/index.md
  - Blogue:
      - blog/index.md