name: Build Swift scripts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.swift'
  pull_request:
    branches:
      - main
    paths:
      - '**.swift'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS 14 configuration
          - os: macos-14
            swift: "5.9"
            command: "xcrun --sdk macosx swiftc -import-objc-header /usr/include/Foundation/Foundation.h scripts/*.swift"
          
          # macOS 15 configuration
          - os: macos-15
            command: "xcrun --sdk macosx swiftc -import-objc-header /usr/include/Foundation/Foundation.h scripts/*.swift"
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Only setup Swift for macOS 14
      - name: Setup Swift
        if: matrix.os == 'macos-14'
        uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}

      - name: Print Swift version
        run: swift --version

      - name: Build Swift scripts
        run: ${{ matrix.command }} || exit 1

  check-builds:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check build matrix status
        run: |
          if [[ "${{ needs.build.result }}" == "failure" || "${{ needs.build.result }}" == "cancelled" ]]; then
            echo "One or more builds failed"
            exit 1
          fi