name: Build Swift scripts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.swift'
  pull_request:
    branches:
      - main
    paths:
      - '**.swift'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS 14 configurations
          - os: macos-14
            swift: "5.9"
            command: "xcrun --sdk macosx swiftc -import-objc-header /usr/include/Foundation/Foundation.h scripts/*.swift"
          
          # macOS 15 configurations
          - os: macos-15
            swift: "6.0"
            command: "xcrun --sdk macosx swiftc -import-objc-header /usr/include/Foundation/Foundation.h scripts/*.swift"
          
          # Ubuntu configuration
          - os: ubuntu-latest
            swift: "5.9"
            command: "swiftc scripts/*.swift"
      fail-fast: false

    steps:
      - name: Install Swift dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y \
            binutils \
            git \
            gnupg2 \
            libc6-dev \
            libcurl4-openssl-dev \
            libedit2 \
            libgcc-9-dev \
            libpython3.8 \
            libsqlite3-0 \
            libstdc++-9-dev \
            libxml2-dev \
            libz3-dev \
            pkg-config \
            tzdata \
            zlib1g-dev
          
          # Download and install Swift
          SWIFT_SIGNING_KEY=A62AE125BBBFBB96A6E042EC925CC1CCED3D1561
          wget -q -O - https://download.swift.org/swift-${matrix.swift}-release/ubuntu2204/swift-${matrix.swift}-RELEASE/swift-${matrix.swift}-RELEASE-ubuntu22.04.tar.gz.sig | gpg --verify - swift-${matrix.swift}-RELEASE-ubuntu22.04.tar.gz
          wget https://download.swift.org/swift-${matrix.swift}-release/ubuntu2204/swift-${matrix.swift}-RELEASE/swift-${matrix.swift}-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-${matrix.swift}-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-${matrix.swift}-RELEASE-ubuntu22.04 /usr/share/swift
          echo "PATH=/usr/share/swift/usr/bin:$PATH" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Swift (non-Ubuntu)
        if: matrix.os != 'ubuntu-latest'
        uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}

      - name: Print Swift version
        run: swift --version

      - name: Build Swift scripts
        run: ${{ matrix.command }} || exit 1

  check-builds:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check build matrix status
        run: |
          if [[ "${{ needs.build.result }}" == "failure" || "${{ needs.build.result }}" == "cancelled" ]]; then
            echo "One or more builds failed"
            exit 1
          fi