name: Update dev website on server

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Save branch name in env var
      run: |
        CURRENT_BRANCH=$(git branch --show-current)
        "BRANCH_TO_USE=$CURRENT_BRANCH" >> $GITHUB_ENV
        echo "Current branch: $CURRENT_BRANCH"
      
    - name: Load secrets from 1Password
      id: onepw_secrets
      uses: 1password/load-secrets-action@v1.3.1
      with:
          export-env: true # Export loaded secrets as environment variables
      env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ACTION_GXFS_WEBSERVER_SSH_HOST: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/kttdw7r3jp6rir7rtgkwk2a22q/ACTION_GXFS_WEBSERVER_SSH_HOST"
          ACTION_GXFS_WEBSERVER_SSH_PORT: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/kttdw7r3jp6rir7rtgkwk2a22q/ACTION_GXFS_WEBSERVER_SSH_PORT"
          ACTION_GXFS_WEBSERVER_SSH_USER: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/kttdw7r3jp6rir7rtgkwk2a22q/ACTION_GXFS_WEBSERVER_SSH_USER"
          ACTION_GXFS_WEBSERVER_SSH_PRIVATE_KEY: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/kttdw7r3jp6rir7rtgkwk2a22q/ACTION_GXFS_WEBSERVER_SSH_PRIVATE_KEY"
          
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.ACTION_GXFS_WEBSERVER_SSH_HOST }}
        username: ${{ env.ACTION_GXFS_WEBSERVER_SSH_USER }}
        key: ${{ env.ACTION_GXFS_WEBSERVER_SSH_PRIVATE_KEY }}
        port: ${{ env.ACTION_GXFS_WEBSERVER_SSH_PORT }}
        script: |
          ./dev_gtfs_org_website_updater.sh ${{ env.BRANCH_TO_USE }}
