name: Fetch new commits from remote repos

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 4 * * *'  # Runs every day at 4 AM UTC

jobs:
  run-swift-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: 1password/load-secrets-action@v2.0.0
        with:
            export-env: true # Export loaded secrets as environment variables
        env:
            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
            GITHUB_TOKEN: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/GitHub generic action token for all repos/credential"

      - name: Run Swift Script
        id: run-swift-script
        run: swift scripts/monitor-remote-repos-for-new-commits.swift
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
